### PR TITLE
Update to LDC 1.13.0 stable release

### PR DESCRIPTION
**Pull request by WebDrake**
https://github.com/ldc-developers/ldc/releases/tag/v1.13.0

### CODE REVIEW

**Comment by WebDrake** [comment]
Note, I haven't touched the bootstrap-of-the-bootstrap compiler version, as it doesn't seem worth it; this can stay stable until it's time for it to be changed.

**Comment by kinke** [comment]
Sure, doesn't matter at all and should work for quite a while. Looks like the snap package upgrades are going to be smooth and painless from now on. :)

**Comment by WebDrake** [comment]
Looks like it!  Thanks so much for your help in getting to this point -- I'm really delighted with the same-version-for-bootstrap design.

It's with the v1.15 release that I need to think about adding extra build flags again (`-lowmem`...?), right?

**Comment by kinke** [comment]
You're welcome, thx for your work on this. - No extra build flags for v1.15, `-lowmem` is purely optional. The only thing you may want to consider for that version is dropping the libtinfo and libedit dependencies (just 2 additional CMake definitions in LLVM cmdline), see https://github.com/ldc-developers/ldc/pull/3019.

**Pull request merged**
