### PR TITLE
Update to LDC 1.10.0 stable release

### PR DESCRIPTION
**Pull request by WebDrake**
https://github.com/ldc-developers/ldc/releases/tag/v1.10.0

### CODE REVIEW

**Comment by WebDrake** [comment]
@JohanEngelen any changes to build setup that I might want to make with this?

**Comment by JohanEngelen** [comment]
Don't think build changes are needed. lgtm

**Comment by JohanEngelen** [comment]
For reference, this is the file that builds the github packages: https://github.com/ldc-developers/ldc/blob/master/.circleci/config.yml

**Comment by WebDrake** [comment]
Yea, I did a diff from 1.9.0 to 1.10.0 and looks like nothing meaningful changed.

**Pull request merged**
