### PR TITLE
Update to LDC 1.9.0 stable release

### PR DESCRIPTION
**Pull request by WebDrake**
https://github.com/ldc-developers/ldc/releases/tag/v1.9.0

### CODE REVIEW

**Comment by JohanEngelen** [comment]
We now ship LTO stdlib binaries with our Github packages. Can you try and test with `cmake -DBUILD_LTO_LIBS=ON` ? 
Testing would be something like: `ldc2 hello.d -of=hello_thin -flto=thin -defaultlib=phobos2-ldc-lto,druntime-ldc-lto`

**Comment by WebDrake** [comment]
Sounds good, but I'll do that as a follow-up patch.  BTW what's the status of LDC 0.17.6 ... ?  I would need that released in order to have a bootstrap compiler that supports LLVM 6.

**Comment by WebDrake** [comment]
@JohanEngelen is that for the LDC or LLVM `cmake` command?  (I checked the ldc-scripts repo but couldn't find any corresponding usage.)

**Comment by kinke** [comment]
The build scripts in ldc-scripts are obsoleted - the official package is built by the [CircleCI config](https://github.com/ldc-developers/ldc/blob/master/.circleci/config.yml). It's for the LDC CMake command line, but also requires `-DD_FLAGS='-w;-flto=thin'`, see [here](https://github.com/ldc-developers/ldc/blob/master/.circleci/config.yml#L268).

**Comment by WebDrake** [comment]
Does that mean that I will need an LTO-supporting LDC to build this?

**Comment by kinke** [comment]
Nope, these flags affect the freshly built compiler compiling its default libs.

**Pull request merged**
